/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/dialogs/ConfirmDialog.vue')['default']
    ErrorDialog: typeof import('./components/dialogs/ErrorDialog.vue')['default']
    InfoDialog: typeof import('./components/dialogs/InfoDialog.vue')['default']
    LoadingDialog: typeof import('./components/dialogs/LoadingDialog.vue')['default']
    PurchaseDialog: typeof import('./components/dialogs/PurchaseDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesDialog: typeof import('./components/dialogs/SalesDialog.vue')['default']
  }
}
